# Generated by Django 3.1.4 on 2020-12-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_auto_20201222_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='track',
            field=models.FileField(upload_to='Songs'),
        ),
    ]
