# Generated by Django 3.1.4 on 2020-12-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_auto_20201222_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='type',
            field=models.IntegerField(verbose_name=((0, 'happy'), (1, 'angry'), (2, 'sad'), (3, 'neutral'), (4, 'general'))),
        ),
    ]
